import { Category, Service, Package, Stat, EventType } from "@/types";

// ── 카테고리 7개 ──
export const CATEGORIES: Category[] = [
  { id: "cat-1", key: "planning", name: "기획서 제작", emoji: "📋", sortOrder: 0 },
  { id: "cat-2", key: "design", name: "시안물 제작", emoji: "🎨", sortOrder: 1 },
  { id: "cat-3", key: "booth", name: "전시부스", emoji: "🏗️", sortOrder: 2 },
  { id: "cat-4", key: "av", name: "영상/음향", emoji: "🎬", sortOrder: 3 },
  { id: "cat-5", key: "mc", name: "MC/진행", emoji: "🎤", sortOrder: 4 },
  { id: "cat-6", key: "event", name: "이벤트 연출", emoji: "🎪", sortOrder: 5 },
  { id: "cat-7", key: "catering", name: "케이터링", emoji: "🍽️", sortOrder: 6 },
];

// ── 서비스 (대표 항목) ──
export const SERVICES: Service[] = [
  {
    id: "svc-1", categoryId: "cat-1", categoryKey: "planning",
    name: "컨퍼런스 기획서", emoji: "📋",
    imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&q=80",
    description: "행사 기획안 + 운영 매뉴얼 포함",
    basePrice: 1500000, isPopular: true, isVisible: true,
    features: [
      { title: "행사 기획안", description: "전체 행사 흐름 설계" },
      { title: "운영 매뉴얼", description: "현장 운영 가이드" },
      { title: "타임테이블", description: "분 단위 일정표" },
      { title: "예산안", description: "항목별 상세 예산" },
    ],
    processSteps: [{ name: "요구사항 확인" }, { name: "초안 작성" }, { name: "피드백 반영" }, { name: "최종 납품" }, { name: "현장 지원" }],
    sizePrices: { small: 1500000, medium: 2200000, large: 3000000 },
    options: [{ name: "영문 번역", price: 500000 }],
    sortOrder: 0,
  },
  {
    id: "svc-2", categoryId: "cat-1", categoryKey: "planning",
    name: "세미나 기획서", emoji: "📝",
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&q=80",
    description: "교육·연수 행사 전문 기획",
    basePrice: 1200000, isPopular: false, isVisible: true,
    features: [{ title: "교육 커리큘럼", description: "강의 구성 설계" }, { title: "연사 섭외 지원", description: "전문 연사 추천" }],
    processSteps: [{ name: "요구사항 확인" }, { name: "초안 작성" }, { name: "피드백 반영" }, { name: "최종 납품" }, { name: "현장 지원" }],
    sizePrices: { small: 1200000, medium: 1800000, large: 2500000 },
    options: [], sortOrder: 1,
  },
  {
    id: "svc-3", categoryId: "cat-2", categoryKey: "design",
    name: "메인 현수막", emoji: "🎨",
    imageUrl: "https://images.unsplash.com/photo-1577962917302-cd874c4e31d2?w=600&q=80",
    description: "대형 현수막 디자인 + 출력",
    basePrice: 800000, isPopular: true, isVisible: true,
    features: [{ title: "디자인 시안", description: "3안 제공" }, { title: "출력·설치", description: "현장 설치 포함" }],
    processSteps: [{ name: "시안 요청" }, { name: "디자인 작업" }, { name: "피드백 반영" }, { name: "출력" }, { name: "설치" }],
    sizePrices: { small: 800000, medium: 1200000, large: 1800000 },
    options: [{ name: "양면 출력", price: 300000 }],
    sortOrder: 0,
  },
  {
    id: "svc-4", categoryId: "cat-2", categoryKey: "design",
    name: "배너·X배너", emoji: "🖼️",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80",
    description: "실내외 배너 디자인 제작",
    basePrice: 400000, isPopular: false, isVisible: true,
    features: [{ title: "디자인 시안", description: "2안 제공" }],
    processSteps: [{ name: "시안 요청" }, { name: "디자인" }, { name: "피드백" }, { name: "출력" }, { name: "배송" }],
    sizePrices: { small: 400000, medium: 600000, large: 900000 },
    options: [], sortOrder: 1,
  },
  {
    id: "svc-5", categoryId: "cat-3", categoryKey: "booth",
    name: "등록 데스크", emoji: "🏗️",
    imageUrl: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600&q=80",
    description: "참가자 등록·접수 부스 설치",
    basePrice: 2000000, isPopular: true, isVisible: true,
    features: [{ title: "데스크 설치", description: "접수대 + 안내판" }, { title: "QR 체크인", description: "전자 접수 시스템" }],
    processSteps: [{ name: "현장 답사" }, { name: "도면 설계" }, { name: "자재 준비" }, { name: "설치" }, { name: "철거" }],
    sizePrices: { small: 2000000, medium: 3000000, large: 4500000 },
    options: [{ name: "QR 체크인", price: 500000 }],
    sortOrder: 0,
  },
  {
    id: "svc-6", categoryId: "cat-4", categoryKey: "av",
    name: "음향 시스템", emoji: "🔊",
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=80",
    description: "라인어레이 스피커 + 전문 엔지니어",
    basePrice: 2500000, isPopular: true, isVisible: true,
    features: [
      { title: "라인어레이 스피커", description: "200W급 전문 스피커 시스템" },
      { title: "전문 엔지니어", description: "현장 음향 엔지니어 배치" },
      { title: "설치·철거", description: "장비 운반 및 세팅" },
      { title: "리허설 지원", description: "사전 음향 체크" },
    ],
    processSteps: [{ name: "요구사항 확인" }, { name: "현장 답사" }, { name: "장비 설치" }, { name: "리허설" }, { name: "행사 운영" }],
    sizePrices: { small: 2500000, medium: 3500000, large: 5000000 },
    options: [{ name: "무선 마이크 추가", price: 200000 }],
    sortOrder: 0,
  },
  {
    id: "svc-7", categoryId: "cat-4", categoryKey: "av",
    name: "LED 스크린", emoji: "📺",
    imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80",
    description: "대형 LED 디스플레이 설치·운영",
    basePrice: 3000000, isPopular: false, isVisible: true,
    features: [{ title: "LED 패널", description: "P3.9 고화질 패널" }, { title: "영상 송출", description: "실시간 영상 운영" }],
    processSteps: [{ name: "규격 확인" }, { name: "장비 준비" }, { name: "설치" }, { name: "테스트" }, { name: "운영" }],
    sizePrices: { small: 3000000, medium: 5000000, large: 8000000 },
    options: [], sortOrder: 1,
  },
  {
    id: "svc-8", categoryId: "cat-5", categoryKey: "mc",
    name: "전문 MC", emoji: "🎤",
    imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&q=80",
    description: "행사 전문 MC 섭외·진행",
    basePrice: 1500000, isPopular: true, isVisible: true,
    features: [{ title: "MC 섭외", description: "경력 5년 이상 전문 MC" }, { title: "대본 작성", description: "행사 시나리오 작성" }],
    processSteps: [{ name: "행사 정보 확인" }, { name: "MC 매칭" }, { name: "대본 작성" }, { name: "리허설" }, { name: "본행사" }],
    sizePrices: { small: 1500000, medium: 2000000, large: 3000000 },
    options: [{ name: "이중언어 MC", price: 1000000 }],
    sortOrder: 0,
  },
  {
    id: "svc-9", categoryId: "cat-6", categoryKey: "event",
    name: "포토존 제작", emoji: "📸",
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
    description: "맞춤형 포토존 디자인·설치",
    basePrice: 1200000, isPopular: true, isVisible: true,
    features: [{ title: "디자인 시안", description: "브랜드 맞춤 디자인" }, { title: "설치·철거", description: "현장 세팅" }],
    processSteps: [{ name: "콘셉트 확인" }, { name: "디자인" }, { name: "제작" }, { name: "설치" }, { name: "철거" }],
    sizePrices: { small: 1200000, medium: 1800000, large: 2500000 },
    options: [{ name: "포토 프린터", price: 500000 }],
    sortOrder: 0,
  },
  {
    id: "svc-10", categoryId: "cat-7", categoryKey: "catering",
    name: "커피/다과", emoji: "☕",
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80",
    description: "프리미엄 커피·다과 케이터링",
    basePrice: 500000, isPopular: false, isVisible: true,
    features: [{ title: "바리스타 서비스", description: "현장 바리스타 운영" }, { title: "다과 세팅", description: "쿠키·과일 등" }],
    processSteps: [{ name: "메뉴 협의" }, { name: "식자재 준비" }, { name: "현장 세팅" }, { name: "서비스 운영" }, { name: "정리" }],
    sizePrices: { small: 500000, medium: 800000, large: 1200000 },
    options: [{ name: "디저트 추가", price: 300000 }],
    sortOrder: 0,
  },
  {
    id: "svc-11", categoryId: "cat-7", categoryKey: "catering",
    name: "뷔페 케이터링", emoji: "🍽️",
    imageUrl: "https://images.unsplash.com/photo-1555244162-803834f70033?w=600&q=80",
    description: "정식 뷔페 케이터링 서비스",
    basePrice: 1500000, isPopular: false, isVisible: true,
    features: [{ title: "메뉴 구성", description: "한식/양식 코스" }, { title: "서빙 인력", description: "전문 서빙 스태프" }],
    processSteps: [{ name: "메뉴 협의" }, { name: "식자재 준비" }, { name: "현장 세팅" }, { name: "서비스 운영" }, { name: "정리" }],
    sizePrices: { small: 1500000, medium: 2500000, large: 4000000 },
    options: [], sortOrder: 1,
  },
  {
    id: "svc-12", categoryId: "cat-4", categoryKey: "av",
    name: "행사 촬영", emoji: "📸",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80",
    description: "전문 촬영팀 현장 촬영",
    basePrice: 800000, isPopular: false, isVisible: true,
    features: [{ title: "사진 촬영", description: "행사 전과정 촬영" }, { title: "보정 납품", description: "200장 이상 보정" }],
    processSteps: [{ name: "촬영 협의" }, { name: "장비 준비" }, { name: "현장 촬영" }, { name: "보정 작업" }, { name: "납품" }],
    sizePrices: { small: 800000, medium: 1200000, large: 2000000 },
    options: [{ name: "드론 촬영", price: 500000 }],
    sortOrder: 2,
  },
];

// ── 패키지 ──
export const PACKAGES: Package[] = [
  {
    id: "pkg-1",
    name: "컨퍼런스 올인원",
    emoji: "🏛️",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&q=80",
    description: "200~500명 규모의 컨퍼런스에 적합한 올인원 패키지",
    eventType: "컨퍼런스",
    discountRate: 20,
    includedServiceIds: ["svc-1", "svc-3", "svc-5", "svc-6", "svc-8", "svc-9"],
    originalPrice: 9500000,
    discountPrice: 7600000,
    isVisible: true,
    sortOrder: 0,
  },
  {
    id: "pkg-2",
    name: "세미나 베이직",
    emoji: "📚",
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&q=80",
    description: "30~100명 규모의 세미나·교육 행사에 적합",
    eventType: "세미나",
    discountRate: 15,
    includedServiceIds: ["svc-2", "svc-4", "svc-6"],
    originalPrice: 2400000,
    discountPrice: 2040000,
    isVisible: true,
    sortOrder: 1,
  },
  {
    id: "pkg-3",
    name: "기업행사 프리미엄",
    emoji: "🏢",
    imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&q=80",
    description: "100~300명 규모의 기업 내부행사·시상식에 적합",
    eventType: "기업행사",
    discountRate: 18,
    includedServiceIds: ["svc-1", "svc-3", "svc-6", "svc-8", "svc-9", "svc-10"],
    originalPrice: 8000000,
    discountPrice: 6560000,
    isVisible: true,
    sortOrder: 2,
  },
];

// ── 행사 유형 (fallback) ──
export const EVENT_TYPES: EventType[] = [
  { id: "et-1", key: "conference", label: "컨퍼런스", emoji: "🏛️", description: "대규모 학술·정책 발표 행사", sortOrder: 0, isVisible: true },
  { id: "et-2", key: "forum", label: "포럼/심포지엄", emoji: "🎓", description: "전문가 토론·발표 중심", sortOrder: 1, isVisible: true },
  { id: "et-3", key: "seminar", label: "세미나/교육", emoji: "📚", description: "강연·연수·워크숍", sortOrder: 2, isVisible: true },
  { id: "et-4", key: "festival", label: "축제/문화행사", emoji: "🎭", description: "공연·전시·체험", sortOrder: 3, isVisible: true },
  { id: "et-5", key: "corporate", label: "기업행사", emoji: "🏢", description: "팀빌딩·송년회·시상식", sortOrder: 4, isVisible: true },
  { id: "et-6", key: "other", label: "기타", emoji: "🤝", description: "직접 구성하기", sortOrder: 5, isVisible: true },
];

// ── 통계 ──
export const STATS: Stat[] = [
  { value: 1200, suffix: "", label: "누적 행사 건수" },
  { value: 10000, suffix: "+", label: "파트너 업체" },
  { value: 4.9, suffix: "/5", label: "평균 만족도" },
  { value: 98, suffix: "%", label: "재계약률" },
];

// ── 인기 서비스 (isPopular: true인 서비스) ──
export const POPULAR_SERVICES = SERVICES.filter((s) => s.isPopular);

// ── 서비스별 상세 설명 ──
export const SERVICE_DETAILS: Record<string, string[]> = {
  "svc-1": [
    "파란컴퍼니의 컨퍼런스 기획서는 행사의 기획부터 현장 운영까지 전 과정을 아우르는 종합 기획 서비스입니다.",
    "10년 이상의 노하우를 바탕으로 행사 목적에 맞는 최적의 프로그램 구성, 예산 관리, 참가자 동선 설계를 제공합니다.",
    "사전 미팅을 통해 고객의 요구사항을 정확히 파악하고, 3회 이상의 피드백 과정을 거쳐 완성도 높은 기획서를 납품합니다.",
  ],
};

// ── 진행 단계별 이모지 매핑 ──
export const PROCESS_STEP_EMOJIS: Record<string, string> = {
  "요구사항 확인": "📋",
  "초안 작성": "✏️",
  "피드백 반영": "💬",
  "최종 납품": "📦",
  "현장 지원": "🤝",
  "시안 요청": "📝",
  "디자인 작업": "🎨",
  "디자인": "🎨",
  "출력": "🖨️",
  "설치": "🔧",
  "배송": "🚚",
  "피드백": "💬",
  "현장 답사": "🏢",
  "도면 설계": "📐",
  "자재 준비": "🧱",
  "철거": "🏗️",
  "장비 설치": "🔊",
  "리허설": "🎵",
  "행사 운영": "🎯",
  "규격 확인": "📏",
  "장비 준비": "⚙️",
  "테스트": "✅",
  "운영": "🎯",
  "행사 정보 확인": "📋",
  "MC 매칭": "🎤",
  "대본 작성": "✏️",
  "본행사": "🎯",
  "콘셉트 확인": "💡",
  "제작": "🔨",
  "메뉴 협의": "📝",
  "식자재 준비": "🥗",
  "현장 세팅": "🍽️",
  "서비스 운영": "👨‍🍳",
  "정리": "🧹",
  "촬영 협의": "📋",
  "현장 촬영": "📸",
  "보정 작업": "🖥️",
  "납품": "📦",
};

// ── 가격 포맷 ──
export function formatPrice(price: number): string {
  return price.toLocaleString("ko-KR");
}
