import { Portfolio } from "@/types";

const S = "https://syzsqdgvculdzfepdlsi.supabase.co/storage/v1/object/public/portfolio";

export const PORTFOLIOS: Portfolio[] = [
  {
    id: "pf-1",
    title: "찾아가는 경기학부모교육",
    eventType: "교육행사대행",
    year: 2025,
    venue: "남양주",
    emoji: "",
    description: "경기도교육청 | 행사운영 | 시안물: 포스터, 카드뉴스, 리플렛, 현수막, 명찰, 엑스배너",
    imageUrl: `${S}/parent-education/photo-15.webp`,
    tags: ["행사운영", "포스터", "카드뉴스", "리플렛", "현수막", "명찰", "엑스배너"],
    gradientType: "corporate",
    isVisible: true,
    slug: "parent-education",
    client: "경기도교육청",
    eventDate: "2025-07-01",
    deliverables: ["포스터", "카드뉴스", "리플렛", "현수막", "명찰", "엑스배너"],
    attendees: "약 150명",
  },
  {
    id: "pf-2",
    title: "중앙아시아 교육협력포럼",
    eventType: "교육행사대행",
    year: 2026,
    venue: "경기도교육청",
    emoji: "",
    description: "경기도교육청 | 포럼 | 시안물: 포스터, 포토존, 리플렛, 엑스배너, 현수막, 명찰, 자료집, 등신대, 전시부스",
    imageUrl: `${S}/international-forum/photo-01.webp`,
    tags: ["포럼", "포스터", "포토존", "리플렛", "엑스배너", "현수막", "명찰", "자료집", "등신대", "전시부스"],
    gradientType: "conference",
    isVisible: true,
    slug: "international-forum",
    client: "경기도교육청",
    eventDate: "2026-01-01",
    deliverables: ["포스터", "포토존", "리플렛", "엑스배너", "현수막", "명찰", "자료집", "등신대", "전시부스"],
    attendees: "약 300명",
  },
  {
    id: "pf-3",
    title: "고양 학교체육 성장 컨퍼런스",
    eventType: "교육행사대행",
    year: 2025,
    venue: "고양",
    emoji: "",
    description: "경기도교육청 | 세미나 | 시안물: 포스터, 포토존, 리플렛, 엑스배너, 현수막, 명찰, 에세이집, 자료집, 등신대",
    imageUrl: `${S}/goyang-conference/photo-02.webp`,
    tags: ["세미나", "포스터", "포토존", "리플렛", "엑스배너", "현수막", "명찰", "에세이집", "자료집", "등신대"],
    gradientType: "seminar",
    isVisible: true,
    slug: "goyang-conference",
    client: "경기도교육청",
    eventDate: "2025-12-01",
    deliverables: ["포스터", "포토존", "리플렛", "엑스배너", "현수막", "명찰", "에세이집", "자료집", "등신대"],
    attendees: "약 200명",
  },
  {
    id: "pf-4",
    title: "KLS 한국어교육 국제학술대회",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "경기도교육청 | 포럼 | 시안물: 포스터, 포토존, 리플렛, 엑스배너, 현수막, 명찰, 등신대, 자료집, 인포그래픽",
    imageUrl: `${S}/kls/photo-03.webp`,
    tags: ["포럼", "포스터", "포토존", "리플렛", "엑스배너", "현수막", "명찰", "등신대", "자료집", "인포그래픽"],
    gradientType: "conference",
    isVisible: true,
    slug: "kls",
    client: "경기도교육청",
    eventDate: "2025-11-01",
    deliverables: ["포스터", "포토존", "리플렛", "엑스배너", "현수막", "명찰", "등신대", "자료집", "인포그래픽"],
    attendees: "약 400명",
  },
  {
    id: "pf-5",
    title: "문화예술클럽 결과공유회",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "한국문화예술교육진흥원 | 행사운영 | 시안물: 포토존, 카드뉴스, 엑스배너, 리플렛, 등신대, 자료집, 기념품",
    imageUrl: `${S}/culture-club-showcase/photo-01.webp`,
    tags: ["행사운영", "포토존", "카드뉴스", "엑스배너", "리플렛", "등신대", "자료집", "기념품"],
    gradientType: "corporate",
    isVisible: true,
    slug: "culture-club-showcase",
    client: "한국문화예술교육진흥원",
    eventDate: "2025-11-01",
    deliverables: ["포토존", "카드뉴스", "엑스배너", "리플렛", "등신대", "자료집", "기념품"],
    attendees: "약 150명",
  },
  {
    id: "pf-6",
    title: "추계 자동차부품산업 세미나",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "자동차부품산업진흥재단 | 세미나 | 시안물: 포스터, 포토존, 엑스배너, 현수막, 명찰, 자료집, 전시패널",
    imageUrl: `${S}/auto-seminar-fall/photo-02.webp`,
    tags: ["세미나", "포스터", "포토존", "엑스배너", "현수막", "명찰", "자료집", "전시패널", "현장사진"],
    gradientType: "seminar",
    isVisible: true,
    slug: "auto-seminar-fall",
    client: "자동차부품산업진흥재단",
    eventDate: "2025-11-01",
    deliverables: ["포스터", "포토존", "엑스배너", "현수막", "명찰", "자료집", "전시패널"],
    attendees: "약 200명",
  },
  {
    id: "pf-7",
    title: "지역사회 역량강화 프로그램",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "한국에너지정보문화재단 | 세미나 | 시안물: 포스터, 엑스배너, 자료집, 쇼핑백, 명찰, 스티커",
    imageUrl: `${S}/community-energy/photo-01.webp`,
    tags: ["세미나", "포스터", "엑스배너", "자료집", "쇼핑백", "명찰", "스티커"],
    gradientType: "seminar",
    isVisible: true,
    slug: "community-energy",
    client: "한국에너지정보문화재단",
    eventDate: "2025-08-01",
    deliverables: ["포스터", "엑스배너", "자료집", "쇼핑백", "명찰", "스티커"],
    attendees: "약 100명",
  },
  {
    id: "pf-8",
    title: "필승해군캠프",
    eventType: "교육행사대행",
    year: 2025,
    venue: "해군 기지",
    emoji: "",
    description: "해군 | 행사운영 | 시안물: 포스터, 엑스배너, 현수막, 폼보드, 일력, 키링",
    imageUrl: `${S}/navy-camp/photo-01.webp`,
    tags: ["행사운영", "포스터", "엑스배너", "현수막", "폼보드", "일력", "키링"],
    gradientType: "corporate",
    isVisible: true,
    slug: "navy-camp",
    client: "해군",
    eventDate: "2025-08-01",
    deliverables: ["포스터", "엑스배너", "현수막", "폼보드", "일력", "키링"],
    attendees: "약 300명",
  },
  {
    id: "pf-9",
    title: "하계 자동차부품산업 세미나",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "자동차부품산업진흥재단 | 세미나 | 시안물: 포스터, 엑스배너, 현수막, 명찰, 자료집, 유튜브 썸네일",
    imageUrl: `${S}/auto-seminar-summer/photo-01.webp`,
    tags: ["세미나", "포스터", "엑스배너", "현수막", "명찰", "자료집", "유튜브 썸네일"],
    gradientType: "seminar",
    isVisible: true,
    slug: "auto-seminar-summer",
    client: "자동차부품산업진흥재단",
    eventDate: "2025-07-01",
    deliverables: ["포스터", "엑스배너", "현수막", "명찰", "자료집", "유튜브 썸네일"],
    attendees: "약 200명",
  },
  {
    id: "pf-10",
    title: "직장인 문화예술클럽 운영",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "한국문화예술교육진흥원 | 행사운영 | 시안물: 상세페이지, 카드뉴스, 인스타그램, 리플렛, 현수막, 배너",
    imageUrl: `${S}/culture-club-operation/photo-01.webp`,
    tags: ["행사운영", "상세페이지", "카드뉴스", "인스타그램", "리플렛", "현수막", "배너"],
    gradientType: "corporate",
    isVisible: true,
    slug: "culture-club-operation",
    client: "한국문화예술교육진흥원",
    eventDate: "2025-05-01",
    deliverables: ["상세페이지", "카드뉴스", "인스타그램", "리플렛", "현수막", "배너"],
    attendees: "약 100명",
  },
  {
    id: "pf-11",
    title: "예술인 권리보호 교육",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "한국예술인복지재단 | 교육 | 시안물: 포스터, 카드뉴스, 엑스배너, 리플렛, 자료집, 웹배너",
    imageUrl: `${S}/artist-rights/photo-01.webp`,
    tags: ["교육", "포스터", "카드뉴스", "엑스배너", "리플렛", "자료집", "웹배너"],
    gradientType: "workshop",
    isVisible: true,
    slug: "artist-rights",
    client: "한국예술인복지재단",
    eventDate: "2025-04-01",
    deliverables: ["포스터", "카드뉴스", "엑스배너", "리플렛", "자료집", "웹배너"],
    attendees: "약 100명",
  },
  {
    id: "pf-12",
    title: "춘계 자동차부품산업 세미나",
    eventType: "교육행사대행",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "자동차부품산업진흥재단 | 세미나 | 시안물: 포스터, 엑스배너, 초대장, 현수막, 명찰, 큐카드",
    imageUrl: `${S}/auto-seminar-spring/photo-01.webp`,
    tags: ["세미나", "포스터", "엑스배너", "초대장", "현수막", "명찰", "큐카드"],
    gradientType: "seminar",
    isVisible: true,
    slug: "auto-seminar-spring",
    client: "자동차부품산업진흥재단",
    eventDate: "2025-03-01",
    deliverables: ["포스터", "엑스배너", "초대장", "현수막", "명찰", "큐카드"],
    attendees: "약 200명",
  },
  {
    id: "pf-13",
    title: "교육감협의회 부스 설치",
    eventType: "교육행사대행",
    year: 2026,
    venue: "서울",
    emoji: "",
    description: "경기도교육청 | 전시 | 시안물: 전시부스, 대형등신대, 테이블등신대",
    imageUrl: `${S}/education-council-booth/photo-01.webp`,
    tags: ["전시", "전시부스", "대형등신대", "테이블등신대"],
    gradientType: "festival",
    isVisible: true,
    slug: "education-council-booth",
    client: "경기도교육청",
    eventDate: "2026-01-01",
    deliverables: ["전시부스", "대형등신대", "테이블등신대"],
  },
  {
    id: "pf-14",
    title: "합동참모본부 SNS 콘텐츠",
    eventType: "콘텐츠 제작",
    year: 2025,
    venue: "서울",
    emoji: "",
    description: "합동참모본부 | 콘텐츠 | 시안물: SNS 콘텐츠, 카드뉴스, 기념일 디자인",
    imageUrl: `${S}/jcs-sns/memorial.webp`,
    tags: ["콘텐츠", "SNS 콘텐츠", "카드뉴스", "기념일 디자인"],
    gradientType: "corporate",
    isVisible: true,
    slug: "jcs-sns",
    client: "합동참모본부",
    eventDate: "2025-01-01",
    deliverables: ["SNS 콘텐츠", "카드뉴스", "기념일 디자인"],
  },
];

export const GRADIENT_MAP: Record<string, string> = {
  conference: "from-primary-100 to-primary-200",
  seminar: "from-success-100 to-emerald-200",
  corporate: "from-accent-100 to-yellow-200",
  festival: "from-pink-100 to-pink-200",
  workshop: "from-indigo-100 to-indigo-200",
};

export const EVENT_TYPES = [
  "전체",
  "교육행사대행",
  "콘텐츠 제작",
];

export const YEARS = ["전체", "2026", "2025"];
